/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author kevin
 */
public class triangleMakerIdentiferScreen extends javax.swing.JFrame {

    /**
     * Creates new form triangleMakerIdentiferScreen
     */
    public triangleMakerIdentiferScreen() {
        initComponents();
        pnlResults.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTriangle = new javax.swing.JPanel();
        lblASegment = new javax.swing.JLabel();
        sldASegment = new javax.swing.JSlider();
        lblASegmentNumber = new javax.swing.JLabel();
        lblBSegment = new javax.swing.JLabel();
        sldBSegment = new javax.swing.JSlider();
        lblBSegmentNumber = new javax.swing.JLabel();
        lblCSegment = new javax.swing.JLabel();
        sldCSegment = new javax.swing.JSlider();
        lblCSegmentNumber = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVerify = new javax.swing.JButton();
        sprAreaOneAreaTwo = new javax.swing.JSeparator();
        pnlResults = new javax.swing.JPanel();
        lblTriangleMakerResult = new javax.swing.JLabel();
        lblTriangleTypeResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblASegment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblASegment.setText("A Segment");

        sldASegment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sldASegment.setMaximum(20);
        sldASegment.setValue(0);
        sldASegment.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldASegmentStateChanged(evt);
            }
        });

        lblASegmentNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblASegmentNumber.setText("0");

        lblBSegment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBSegment.setText("B Segment");

        sldBSegment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sldBSegment.setMaximum(20);
        sldBSegment.setValue(0);
        sldBSegment.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldBSegmentStateChanged(evt);
            }
        });

        lblBSegmentNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBSegmentNumber.setText("0");

        lblCSegment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCSegment.setText("C Segment");

        sldCSegment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sldCSegment.setMaximum(20);
        sldCSegment.setValue(0);
        sldCSegment.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldCSegmentStateChanged(evt);
            }
        });

        lblCSegmentNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCSegmentNumber.setText("0");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/triangle.png"))); // NOI18N

        btnVerify.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVerify.setText("Verify");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        lblTriangleMakerResult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTriangleMakerResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTriangleMakerResult.setText("Makes A Triangle?");

        lblTriangleTypeResult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTriangleTypeResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTriangleTypeResult.setText("Triangle Type");

        javax.swing.GroupLayout pnlResultsLayout = new javax.swing.GroupLayout(pnlResults);
        pnlResults.setLayout(pnlResultsLayout);
        pnlResultsLayout.setHorizontalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTriangleMakerResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResultsLayout.createSequentialGroup()
                        .addComponent(lblTriangleTypeResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlResultsLayout.setVerticalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTriangleMakerResult)
                .addGap(26, 26, 26)
                .addComponent(lblTriangleTypeResult)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTriangleLayout = new javax.swing.GroupLayout(pnlTriangle);
        pnlTriangle.setLayout(pnlTriangleLayout);
        pnlTriangleLayout.setHorizontalGroup(
            pnlTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTriangleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sprAreaOneAreaTwo)
                    .addGroup(pnlTriangleLayout.createSequentialGroup()
                        .addGroup(pnlTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTriangleLayout.createSequentialGroup()
                                .addGroup(pnlTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlTriangleLayout.createSequentialGroup()
                                        .addComponent(lblASegment)
                                        .addGap(18, 18, 18)
                                        .addComponent(sldASegment, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTriangleLayout.createSequentialGroup()
                                        .addComponent(lblBSegment)
                                        .addGap(18, 18, 18)
                                        .addComponent(sldBSegment, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(pnlTriangleLayout.createSequentialGroup()
                                        .addComponent(lblCSegment)
                                        .addGap(18, 18, 18)
                                        .addComponent(sldCSegment, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCSegmentNumber)
                                    .addComponent(lblASegmentNumber)
                                    .addComponent(lblBSegmentNumber)))
                            .addGroup(pnlTriangleLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlTriangleLayout.setVerticalGroup(
            pnlTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTriangleLayout.createSequentialGroup()
                .addGroup(pnlTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTriangleLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnlTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblASegment)
                            .addComponent(sldASegment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblASegmentNumber))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBSegment)
                            .addComponent(sldBSegment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBSegmentNumber))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCSegment)
                            .addComponent(sldCSegment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCSegmentNumber))
                        .addGap(18, 18, 18)
                        .addComponent(btnVerify))
                    .addGroup(pnlTriangleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(sprAreaOneAreaTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTriangle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTriangle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // TODO add your handling code here:
        pnlResults.setVisible(true);
        
        int a = sldASegment.getValue();
        int b = sldBSegment.getValue();
        int c = sldCSegment.getValue();
        
        if(a < b + c && b < a + c && c < a + b){
            lblTriangleMakerResult.setText("A Triangle can be made");
            
            if(a == b && b == c){
                lblTriangleTypeResult.setText("Triangle type: Equilateral");
            }
            else if (a != b && b != c && c!= a){
                lblTriangleTypeResult.setText("Triangle type: Scalene");
            }
            else{
                lblTriangleTypeResult.setText("Triangle type: Isoceles");
            }
            
        }
        else{
            lblTriangleMakerResult.setText("A triangle cannot be made");
            lblTriangleTypeResult.setText(" ");
        }
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void sldASegmentStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldASegmentStateChanged
        // TODO add your handling code here:
        lblASegmentNumber.setText(Integer.toString(sldASegment.getValue()));
    }//GEN-LAST:event_sldASegmentStateChanged

    private void sldBSegmentStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldBSegmentStateChanged
        // TODO add your handling code here:
        lblBSegmentNumber.setText(Integer.toString(sldBSegment.getValue()));
    }//GEN-LAST:event_sldBSegmentStateChanged

    private void sldCSegmentStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldCSegmentStateChanged
        // TODO add your handling code here:
        lblCSegmentNumber.setText(Integer.toString(sldCSegment.getValue()));
    }//GEN-LAST:event_sldCSegmentStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(triangleMakerIdentiferScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(triangleMakerIdentiferScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(triangleMakerIdentiferScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(triangleMakerIdentiferScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new triangleMakerIdentiferScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblASegment;
    private javax.swing.JLabel lblASegmentNumber;
    private javax.swing.JLabel lblBSegment;
    private javax.swing.JLabel lblBSegmentNumber;
    private javax.swing.JLabel lblCSegment;
    private javax.swing.JLabel lblCSegmentNumber;
    private javax.swing.JLabel lblTriangleMakerResult;
    private javax.swing.JLabel lblTriangleTypeResult;
    private javax.swing.JPanel pnlResults;
    private javax.swing.JPanel pnlTriangle;
    private javax.swing.JSlider sldASegment;
    private javax.swing.JSlider sldBSegment;
    private javax.swing.JSlider sldCSegment;
    private javax.swing.JSeparator sprAreaOneAreaTwo;
    // End of variables declaration//GEN-END:variables
}
