/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import java.awt.Font;

/**
 *
 * @author kevin
 */
public class AkinatorCloneScreen extends javax.swing.JFrame {

    /**
     * Creates new form AkinatorCloneScreen
     */
    public AkinatorCloneScreen() {
        initComponents();
        lblBalloonText.setText("<html>I thought of a number between <strong>1</strong> and <strong>5</strong>.<br>Can you guess which one it was?</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAkinator = new javax.swing.JLabel();
        lblBalloonText = new javax.swing.JLabel();
        lblBalloon = new javax.swing.JLabel();
        lblYourGuesstxt = new javax.swing.JLabel();
        spnYourGuess = new javax.swing.JSpinner();
        btnConfirmGuess = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAkinator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/akinator.png"))); // NOI18N
        getContentPane().add(lblAkinator, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        lblBalloonText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBalloonText.setForeground(new java.awt.Color(0, 0, 0));
        lblBalloonText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBalloonText.setText("jLabel3");
        getContentPane().add(lblBalloonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 135, 250, 120));

        lblBalloon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/balloon.png"))); // NOI18N
        getContentPane().add(lblBalloon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 154));

        lblYourGuesstxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblYourGuesstxt.setText("YOUR GUESS:");
        getContentPane().add(lblYourGuesstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        spnYourGuess.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnYourGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 80, -1));

        btnConfirmGuess.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConfirmGuess.setText("CONFIRM GUESS !");
        btnConfirmGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmGuessActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmGuessActionPerformed
        // TODO add your handling code here:
        int cpu_number = (int) Math.rint(1 + Math.random()* (5 - 1));
        int your_guess = Integer.parseInt(spnYourGuess.getValue().toString());
        
        String win = "<html>Congratulations! You Discovered the number (<strong>" + cpu_number + "</strong>)</html>";
        String lose = "<html>Too bad! I thought the value <strong>" + cpu_number + "</strong>.</html>";
        
        String res = (cpu_number == your_guess) ? win : lose;
        
        // to insert a new font, use lblBalloonText.setFont(new Font("<font_name>", Font.PLAIN, <font_size>));
        lblBalloonText.setText(res);
    }//GEN-LAST:event_btnConfirmGuessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AkinatorCloneScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AkinatorCloneScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AkinatorCloneScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AkinatorCloneScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AkinatorCloneScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmGuess;
    private javax.swing.JLabel lblAkinator;
    private javax.swing.JLabel lblBalloon;
    private javax.swing.JLabel lblBalloonText;
    private javax.swing.JLabel lblYourGuesstxt;
    private javax.swing.JSpinner spnYourGuess;
    // End of variables declaration//GEN-END:variables
}
